/**
 * Central Error Code Registry (CODING_STANDARDS P2.5.1).
 * All DomainError instances MUST use an enum member — never a raw string literal.
 */
export enum ErrorCode {
  CACHE_ERROR = "CACHE_ERROR",
  CONFLICT = "CONFLICT",
  DOMAIN_GUARD_BLOCKED = "DOMAIN_GUARD_BLOCKED",
  EMBEDDING_ERROR = "EMBEDDING_ERROR",
  EXTERNAL_API_ERROR = "EXTERNAL_API_ERROR",
  FORBIDDEN = "FORBIDDEN",
  INVALID_CONTENT_TYPE = "INVALID_CONTENT_TYPE",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  LLM_ERROR = "LLM_ERROR",
  NOT_FOUND = "NOT_FOUND",
  PDF_PARSE_FAILED = "PDF_PARSE_FAILED",
  RATE_LIMITED = "RATE_LIMITED",
  RETRIEVAL_ERROR = "RETRIEVAL_ERROR",
  SSRF_BLOCKED = "SSRF_BLOCKED",
  UNAUTHORIZED = "UNAUTHORIZED",
  VALIDATION_FAILED = "VALIDATION_FAILED",
}

export const errorStatusMap: Record<ErrorCode, number> = {
  [ErrorCode.CACHE_ERROR]: 500,
  [ErrorCode.CONFLICT]: 409,
  [ErrorCode.DOMAIN_GUARD_BLOCKED]: 422,
  [ErrorCode.EMBEDDING_ERROR]: 502,
  [ErrorCode.EXTERNAL_API_ERROR]: 502,
  [ErrorCode.FORBIDDEN]: 403,
  [ErrorCode.INVALID_CONTENT_TYPE]: 415,
  [ErrorCode.INTERNAL_ERROR]: 500,
  [ErrorCode.LLM_ERROR]: 502,
  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.PDF_PARSE_FAILED]: 422,
  [ErrorCode.RATE_LIMITED]: 429,
  [ErrorCode.RETRIEVAL_ERROR]: 500,
  [ErrorCode.SSRF_BLOCKED]: 422,
  [ErrorCode.UNAUTHORIZED]: 401,
  [ErrorCode.VALIDATION_FAILED]: 422,
};
